CREATE TABLE APP.ANKIETA
(
ANSWER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
WORKPLACE_NAME VARCHAR(24) NOT NULL,
WORK_ROLE VARCHAR(26),
WORK_SAT VARCHAR(26),
ChANGE_WORK VARCHAR(3),
WHERE_WANNA VARCHAR(26),
PAYMENT VARCHAR(26),
UNIQUE (ANSWER_ID)
)